# Generated by Django 4.2 on 2023-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, null=True, to="blog.tag"),
        ),
    ]
