# Generated by Django 4.2.6 on 2023-11-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
